sections:
  -
    title: Service Object
    id: service-object
    description: /services/service-object.md
    attributes: /services/service-object.yml
    filters: /services/service-object.yml
    response: /services/service-object.json
    response_title: OBJECT
  -
    title: List all Services
    id: list-all-services
    description: /services/list-all-services.md
    code: /services/list-all-services.py
    code_type: GET
    code_url: /api/services/
    response: /services/list-all-services.json
  -
    title: Get a Service
    id: get-a-service
    description: /services/get-a-service.md
    code: /services/get-a-service.py
    code_type: GET
    code_url: /api/services/<id>/
    response: /services/get-a-service.json
  -
    title: Create a Service
    id: create-a-service
    description: /services/create-a-service.md
    code: /services/create-a-service.py
    code_type: POST
    code_url: /api/services/
    response: /services/create-a-service.json
  -
    title: Update a Service
    id: update-a-service
    description: /services/update-a-service.md
    code: /services/update-a-service.py
    code_type: PUT
    code_url: /api/services/<id>/
    response: /services/update-a-service.json
