name: CI
on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: yarn install

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8.16a'

    - name: install
      run: |
        make install
        harrier --version
    - name: lint
      run: |
        make lint
    - name: Check Actions
      env:
        TC_API_KEY: ${{ secrets.TC_API_KEY }}
      run: python ./scripts/check_actions.py
    - run: harrier build
